apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: global-bank
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: global-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - image: localhost:32000/brainupgrade/global-bank-account:1.0.0
        name: account
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
          - name: java.security.egd
            value: file:/dev/./urandom
          - name: server.port
            value: "80"
          - name: spring.datasource.url
            value: jdbc:mariadb://account-db.global-bank.svc.cluster.local:3306/account
          - name: spring.datasource.driverClassName
            value: "org.mariadb.jdbc.Driver"
          - name: spring.jpa.database-platform
            value: "org.hibernate.dialect.MariaDBDialect"
          - name: spring.jpa.properties.hibernate.dialect
            value: "org.hibernate.dialect.MariaDBDialect"
          - name: spring.datasource.username
            value: "account"
          - name: spring.datasource.password
            value: "account"
          - name: feign.url-customer-service
            value: "customer.global-bank.svc.cluster.local/customer"
          - name: feign.url-auth-service
            value: "authentication.global-bank.svc.cluster.local/auth-ms"
          - name: feign.url-transaction-service
            value: "transaction.global-bank.svc.cluster.local/transaction-ms"