spring.application.name=account
server.port=8086

#SERVLET PATH
server.error.include-stacktrace=never
server.servlet.context-path=/account

#H2
spring.datasource.url=jdbc:h2:mem:account
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.sql.init.mode=always



feign.url-customer-service=${CUSTOMER_SERVICE_URL:localhost:8085/customer}
feign.url-auth-service=${AUTH_SERVICE_URL:localhost:8084/auth}
feign.url-transaction-service=${TRANSACTION_SERVICE_URL:localhost:8087/transaction}

management.endpoints.web.exposure.include=health,info
management.endpoints.access.default=none
management.endpoint.health.access=read-only
management.endpoint.info.access=read-only
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true